### ISSUE TITLE
Search should consider consecutive letters only

### ISSUE THREAD

**Issue by damithc** [GitHubExtensions/Git-Labels#4]
e.g.
`med` should not match `mergeApproved`
![image](https://user-images.githubusercontent.com/1673303/27571020-1f00b6ec-5b35-11e7-8931-3e384c5c5a57.png)

**Comment by jiajunGit** [comment]
@damithc I have modified the search algo in commit [b1fdeab](../commit/b1fdeabf821478a08e2db77a691a7d58d2f82821) to consider only consecutive characters but it is more forgiving towards characters like . or - or spaces so if you type aallocated, it will match a-allocated

I will keep this issue open because I want to see if this search algo is what you have in mind. If this is the search algo you want, you can close the issue. If not, you can state some modifications you want to be made to the search algo and I will try to alter it.

**Comment by damithc** [comment]
> I will keep this issue open because I want to see if this search algo is what you have in mind. If this is the search algo you want, you can close the issue. If not, you can state some modifications you want to be made to the search algo and I will try to alter it.

Roger that :+1:

**Comment by damithc** [comment]
The current behavior is good. Closing for now. Will reopen if something comes up.
